// const
export const GET_DEFAULT_LIST_PENDING = 'GET_DEFAULT_LIST_PENDING'
export const GET_DEFAULT_LIST_FULFILLED = 'GET_DEFAULT_LIST_FULFILLED'
export const GET_DEFAULT_LIST_REJECTED = 'GET_DEFAULT_LIST_REJECTED'



